### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sato310-sato** [sato310-sato/furima-29788#10]
#URL
https://furima-29788.herokuapp.com/

#Basic認証のIDとパスワード
ID: admin
パスワード:2222

#出品者用のメールアドレスとパスワード
メールアドレス: test@test.com
パスワード: test1234

#購入者用のメールアドレスとパスワード
メールアドレス: test@test1.com
パスワード: test1234

#購入用カードの番号・期限・セキュリティコード
カード番号:4242424242424242
期限:12/24
セキュリティコード:123

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**・商品購入時にエラーハンドリングができていない**
商品購入の際に無効な値で購入しようとするとユーザー登録、商品出品時と同様にエラーメッセージが表示されるように
しましょう

修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by sato310-sato** [comment]
・商品購入時のエラーハンドリングを修正致しました。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂いたところ、前回、指摘した修正箇所の修正が確認できなかったため
本番環境で修正内容が反映されているか確認お願いします！

【前回の修正箇所】
**・商品購入時にエラーハンドリングができていない**

修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by sato310-sato** [comment]
再度プルリクエストを行う必要があるのだと勘違いしておりました。
お手数おかけしますが宜しくお願い致します。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
